### ISSUE TITLE
xdg-portal question

### ISSUE THREAD

**Issue by leiserfg** [sjcobb2022/nixos-config#1]
Hi, I'm struggling to set up hyprland in home-manager myself, is this enough to make the portal work?

https://github.com/sjcobb2022/nixos-config/blob/677fd8fbccfe4b5f4dd13112895d0228a44f9de2/home-manager/common/features/desktop/hyprland/default.nix#L11

**Comment by sjcobb2022** [comment]
Hi man,

Getting xdg portals working is a massive pain with home manager. So no this doesn't make it work, it bust makes it accessible in packages. I'm still trying to figure this out and get this to work but I haven't really come accross a solution. 

Here is the solution used in nixpkgs for xdg.portal.wlr

https://github.com/NixOS/nixpkgs/blob/fa793b06f56896b7d1909e4b69977c7bf842b2f0/nixos/modules/config/xdg/portals/wlr.nix#L61-L65

You should be able to do something like that in home manager, as systemd.user.services is available: https://github.com/nix-community/home-manager/blob/ee5673246de0254186e469935909e821b8f4ec15/modules/systemd.nix#L106

I'll see if I can come up with something soon. Otherwise, you can just about rely on  this:

https://github.com/sjcobb2022/nixos-config/blob/677fd8fbccfe4b5f4dd13112895d0228a44f9de2/hosts/slaptop/default.nix#L78-L81

**Comment by sjcobb2022** [comment]
Hi @leiserfg 

I just want to let you know that this issue is now obsolete, as thanks to Misterio77, there is now a home manager module that provides XDG portal support. It is currently in Home manager unstable, but I have it as a module currently in `modules/home-manager/xdg-portal.nix`.
