### ISSUE TITLE
GreetD with Tuigreet shows terminal output before starting Hyprland

### ISSUE THREAD

**Issue by LuposX** [sjcobb2022/nixos-config#3]
Hello, I've been using your GreeD config(https://github.com/sjcobb2022/nixos-config/blob/main/hosts/common/optional/), which works great besides one point.

After login in with GreetD, for a short amount of time it shows the terminal(see video around 00:18), before starting hyprland. Is there a way to get rid of that?

https://github.com/user-attachments/assets/d5d4f2ae-9c1f-4863-81f3-80d5a0078b53

**Comment by sjcobb2022** [comment]
Ah yeh. Instead of booting from the wayland-session like we setup here: https://github.com/sjcobb2022/nixos-config/blob/2e29a57cc067953785f29dc538ce69139c888ede/hosts/common/optional/greetd.nix#L7, you could set the default session to be Hyprland and then redirect logs to /dev/null

https://nixos.wiki/wiki/Greetd for setting up a default session

Hyprland > /dev/null perhaps?

Or exec > /dev/null 2>&1?

**Comment by LuposX** [comment]
Yeah that works, I do it now without tuigreet. 
Thanks!
